apiVersion: v1
kind: Service
metadata:
  name: stimlite-service
spec:                      
  selector:      
    app: stimlite            
  ports:                    
  - port: 8080                
    targetPort: 8501
    nodePort: 32443
  type: NodePort 
  

















